module.exports = [
	{label: "ORBIS (2014)", links: [{label: "Interactive Site", link: "http://orbis.stanford.edu/"}], tags: ["net", "geo"], image: "orbis_l.png", contentFile: "orbis2014.md", description: "An upgrade of the original ORBIS project, with additional functionality."},
	{label: "Catal Hoyuk Participant Network", links: [{label: "Interactive Site", link: "http://catalhoyuk.stanford.edu/network/"}], tags: ["net", "text"], image: "catalnetwork_l.png", contentFile: "catalnetwork.md", description: "Multimodal network view of the archaeologists and support staff of the Catal Hoyuk dig."},
	{label: "Kindred Britain", links: [{label: "Interactive Site", link: "http://kindred.stanford.edu/"}], tags: ["net", "geo", "story"], image: "kindred_l.png", contentFile: "kindred.md", description: "An interactive network perspective of British cultural elites."},
	{label: "D3 Community Exploration", links: [{label: "Interactive Site", link: "http://emeeks.github.io/introspect/"}], tags: ["net", "text"], image: "d3community_l.png", contentFile: "d3introspect.md", description: "An examination of D3 community members and D3 project similarity."},
	{label: "OR-7 Map", links: [{label: "Interactive Map", link: "http://hajrameeks.com/journey.html"}], tags: ["geo", "story"], image: "journey_l.png", contentFile: "journey.md", description: "The track of a wolf in California using a satellite projection overlaid on watercolor."},
	{label: "Topotime", links: [{label: "Topotime Gallery & Sandbox", link: "http://dh.stanford.edu/topotime/"}, {label: "Topotime Repo", link: "https://github.com/kgeographer/Topotime"}], tags: ["time", "geo"], image: "topotime_l.png", contentFile: "topotime.md", description: "Computing and visualizing complex temporal representation"},
	{label: "ORBIS (2012)", links: [{label: "Interactive Site", link: "http://orbis.stanford.edu/orbis2012/"}], tags: ["net", "geo"], image: "orbis2012_l.png", contentFile: "orbis2012.md", description: "A historical transportation network model of the Roman Empire."},
	{label: "ORBIS|via", links: [{label: "Interactive Site", link: "http://orbis.stanford.edu/via/"}], tags: ["net", "geo", "game"], image: "orbisvia_l.png", contentFile: "orbisvia.md", description: "A situated perspective on the ORBIS network, inspired by Oregon trail."},
	{label: "An Introduction to Networks", links: [{label: "Interactive Site", link: "http://dhs.stanford.edu/dh/networks/"}], tags: ["net"], image: "networktoy_l.png", contentFile: "networktoy.md", description: "Several network analysis and representation concepts in an interactive toy."},
	{label: "Species Biodiversity Database Analysis", links: [], tags: ["net", "text", "geo"], image: "sdbw_l.png", contentFile: "species.md", description: "Analysis of the texture of species biodiversity databases."},
	{label: "Velocipedia", tags: ["game", "story"], links: [{label: "Animation", link: "https://www.youtube.com/watch?v=gxBhCra_EEY"}, {label: "Interactive (Requires Flash)", link: "http://elijahmeeks.com/misc/bluesky.swf"}], image: "velocipedia_l.png", contentFile: "velocipedia.md", description: "A prototype of an animated encylopedia of verbs and processes."},
	{label: "Animating Networks", tags: ["net"], links: [{label: "Animation", link: "https://www.youtube.com/watch?v=PIFmjhK2Qao"}], image: "humanities_networks_l.png", contentFile: "animatednetworks.md", description: "High resolution animation of filtering and laying out network visualizations"},
	{label: "Wikipedia Edits During the Arab Spring", links: [{label: "Animation", link: "https://www.youtube.com/watch?v=z3Wo22jl4Ac"}], tags: ["net", "text"], image: "wikipedia_l.png", contentFile: "wikipediaedits.md", description: "A seven day rolling window of edits and shared editors."}
]
